### ISSUE TITLE
How to embed fall?

### ISSUE THREAD

**Issue by aarroyoc** [remexre/fall#1]
Hi,

Thanks for building fall, it's something I've been looking for. However, I can't embed fall in my program. Apparently, the cst module is private which is needed to build a Lit. 

I can help you but I don't know how you'd like to implement the API to make available outside without losing the scope data (maybe a higher level Lit constructor).

Greetings, Adrián

**Comment by remexre** [comment]
`Lit` should be reexported at the top level? i.e., this should (and does on my machine) work:

```rust
extern crate fall;

use fall::{Lit, Term};

fn main() {
    println!("{}", Lit("foo".into(), vec![Term::Num(42).into()]));
}
```

**Comment by aarroyoc** [comment]
Oh, yes, it works!

I've been trying to do it with parse, as you do in the tests. This way it also works, thanks!
